problem:
  N: 3 # state dimension for PS problem; set to 3, 5, or 11
  domain_t: [0.0, 0.5]
  domain_x: [-1.5, 1.5]
  tf: 0.5
  r: 1.0
  a: 1.0
  b: 1.0
  c: 0.5
  alpha: -2.0
  beta: 2.0
  base_sigma: 0.1
  epsilon: 0.3
  theta: 0.78539816339

train:
  mode: pi  # pi or direct
  Ni: 9000 # number of initial points ( 1000 * N^2)
  num_iters: 500
  num_epochs: 5000
  lr: 1.0e-3
  seed: 0
  unit: 64
